language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: LBAIDl9lkef6waBq53qiNubne5BZfxDfJl+XfcmPtjjbkEc+aIjuJl9T1HyC/ru1FRu/UB3h3pKn9fQalni5n1VCU/7SFsNNDg3dbw2hVO2I08jNhNepMw7WYlPNYs3t3Foei6nldt2CsFLfrYsHUd4gwxpZJzscRm09jZr8WZczpl61vdYeuYZXUXRozCmAdlZcDLE7csIR+3W4pu0+4wUGwb71WpTALPxTHwYK7CYa9WjjIQe0ww6cedUBlGBSeVQBHOYcvPh0iZYoGcjyu9R1tACMZmDDWor0XNozB+WEcSGGPBzDFjHdu22MGVQN+86ssvNc4E9Xam2NmoMGSTA4rUIcWT+m3a7Ttr6MdWi9iai95PszG44xFcU4WRAEsHIfzRKxZ8a84CIWsJxZ4GK6nO0wg5Y6pIJRdeoRWOZR+e4LqH/6g2GROPdgnmWyJq5WuBT6hilEOnNTynOWDEX0cIGtImUYKGDD0CJs1lSctw2cPW+rHiUYGTDH4xoPT6V+CURmVgKzBU50xyD91tDQQGuogAdhdQg9kLeXV/ZqkcPCweUbKtyyqjHPfcdRTLIN4PbKDDMZy/WgOhklpiGUoAtllWiRL2Gcyy2gouaqZgmlV/TYcD6lvsBDUVc03u2JFqveBLZNuAh4GXrs0E82UmUMVJnPMp6stz7OIbk=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: LaedWC1igLr5yHoPdwG7sP/HO1b9qQL6U1Az0GRYMNRyrzg5NUrxJuUs0vZcFoUQXVhA3b3YmeL1yA8za5VGYwRXhpcrT0iAHzfNWZMRHn/d/pWwCzcd+FIit5/8CDS1bVgzR0IaSLwpDf6GNPXJE+KadhxurhQPgK2mty3gZ/PfIGIY5IaStuJkxxQpqK/QvZaJKLHGwiOvA50OTcEnFFpsOqVqFoD3NgGQvX78u4s1GY9274lzro84LFgc1u8CChvmxOjBgRiJGs3G3BYU6wRFxHQ9m1HDo6Yk53wvmAdBtYrrE6fFRC94KFpaV7xn3JNANdiYbIFNgVcPwUv3gaSVXvvFy/7R0YxHQAJt/f42Or+rvDvHqMP/zamaQl4B7eU46SQbllL8jce217n7l0v46SEwmvFbe2MzHjeRcTcjEBAJ6bEb52AQq/Wpc8KBM3Of+U55tRiCy8i+k30Q2P8u+j9UQAPQh3GQOx1+nD5+qDNtVbFGkgUjYVHcOQcQ7/SKfPzoe8gWZeJJyy1H6Q2RQZ5ItH5kSWe9vdZzQLip57sdrxL0EiOTmJb2X2PZU8PzWhGF7jMjA8S/ExIKP3i5wKS+pnRuC8Jbq8KCvYJ0p1tRNE40MOs7XKGCfF2tABymOFmDtIX/xId4h8W22OnksFjSiUS4CsCvpBDhBZM=
sudo: false
